-- Seed local D1 with 4 published case studies from production.
-- Idempotent: re-running replaces existing rows by primary key.

DELETE FROM blocks WHERE case_study_id IN ('8h1nM05brs4UI9JxF112u','_W3CNdKyEroebstm03uOy','7gm2H-4lgOgDL9MWth-7e','Ki7vphBTNqabA9jhaf5Ub');
DELETE FROM case_studies WHERE id IN ('8h1nM05brs4UI9JxF112u','_W3CNdKyEroebstm03uOy','7gm2H-4lgOgDL9MWth-7e','Ki7vphBTNqabA9jhaf5Ub');

INSERT INTO case_studies (id, slug, title, summary, status, featured, sort_order, created_at, updated_at, published_at) VALUES ('8h1nM05brs4UI9JxF112u', 'estelar', 'Estelar', 'As Art Director, I led the logo and campaign design for the launch of Salami Súper Especial Estelar in New York—the first 100% Dominican salami introduced to the U.S. market. 

The concept “Made by Tú Sabe” was created as a bold seal of authenticity, blending cultural pride with a familiar Dominican expression to connect with the community. I also directed the product and food photography, using a vibrant color palette to highlight the brand’s identity and showcase the versatility of Estelar in ', 'published', 1, 0, 1777962243227, 1777997572348, 1777997572348);
INSERT INTO case_studies (id, slug, title, summary, status, featured, sort_order, created_at, updated_at, published_at) VALUES ('_W3CNdKyEroebstm03uOy', 'alkasa-30th-aniversary', 'Alkasa - 30th Aniversary', 'As Art Director, I led the branding and visual identity for Alkasa’s 30th anniversary, crafting a logo and graphic language that celebrate travel and exploration.', 'published', 1, 0, 1777962093133, 1777997570911, 1777997570911);
INSERT INTO case_studies (id, slug, title, summary, status, featured, sort_order, created_at, updated_at, published_at) VALUES ('7gm2H-4lgOgDL9MWth-7e', 'restaurante-temporada-temporada-chifa', 'Restaurante Temporada - Temporada Chifa', 'Rediseño de logo para Temporada Chifa y diseño de los diferentes menús (menú de platos - menú tragos y cocteles - carta de vinos) durante esa  temporada especializada en la gastronomía Chifa.', 'published', 0, 0, 1777963435453, 1777997651990, 1777997651990);
INSERT INTO case_studies (id, slug, title, summary, status, featured, sort_order, created_at, updated_at, published_at) VALUES ('Ki7vphBTNqabA9jhaf5Ub', 'liquid-beer', 'Liquid Beer', 'Liquid Beer | 10 Years was developed as a proposal for an internal design contest celebrating the agency’s 10-year milestone. The concept, “Helping Hands,” was inspired by the collective effort behind every creative achievement — the hands that build, push ideas forward, and support one another through tight deadlines and challenges.

 The goal was to translate this spirit of collaboration into a bold, memorable beer identity that embodied teamwork, growth, and shared success. Through expressive', 'published', 0, 0, 1777961922820, 1777997543189, 1777997283939);

INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('iDzfyeGG9lOiGQlPpmuJQ', '7gm2H-4lgOgDL9MWth-7e', 0, 'single', '7gm2H-4lgOgDL9MWth-7e/iDzfyeGG9lOiGQlPpmuJQ.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('0HbROjJBAxoqchxOL2XF2', '7gm2H-4lgOgDL9MWth-7e', 1, 'single', '7gm2H-4lgOgDL9MWth-7e/0HbROjJBAxoqchxOL2XF2.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('Pe8Nisdfp7v1i8cE-3B3V', '7gm2H-4lgOgDL9MWth-7e', 2, 'single', '7gm2H-4lgOgDL9MWth-7e/Pe8Nisdfp7v1i8cE-3B3V.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('enPa17xGOvx5KyMftxX_-', '8h1nM05brs4UI9JxF112u', 0, 'single', '8h1nM05brs4UI9JxF112u/enPa17xGOvx5KyMftxX_-.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('9Fr2jeclHpyFY5B0Ti5qO', '8h1nM05brs4UI9JxF112u', 1, 'single', '8h1nM05brs4UI9JxF112u/9Fr2jeclHpyFY5B0Ti5qO.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('pIrPtZ2VZQhhcT6I4T2TE', '8h1nM05brs4UI9JxF112u', 2, 'single', '8h1nM05brs4UI9JxF112u/pIrPtZ2VZQhhcT6I4T2TE.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('TbAz6Y_APba4iiJc0R97z', '8h1nM05brs4UI9JxF112u', 3, 'single', '8h1nM05brs4UI9JxF112u/TbAz6Y_APba4iiJc0R97z.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('lze0ZnFfoqALFlFNnCEB6', '8h1nM05brs4UI9JxF112u', 4, 'single', '8h1nM05brs4UI9JxF112u/lze0ZnFfoqALFlFNnCEB6.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('GvKDtbwEPhdzUTWm5ruIK', '8h1nM05brs4UI9JxF112u', 5, 'single', '8h1nM05brs4UI9JxF112u/GvKDtbwEPhdzUTWm5ruIK.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('J_C--U9J_RfttFX-izJOr', '8h1nM05brs4UI9JxF112u', 6, 'single', '8h1nM05brs4UI9JxF112u/J_C--U9J_RfttFX-izJOr.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('3jurAmdFDes708yzdEsyf', '8h1nM05brs4UI9JxF112u', 7, 'single', '8h1nM05brs4UI9JxF112u/3jurAmdFDes708yzdEsyf.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('GP3_AW4eXrjXwTtcgM_xn', '8h1nM05brs4UI9JxF112u', 8, 'single', '8h1nM05brs4UI9JxF112u/GP3_AW4eXrjXwTtcgM_xn.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('bRcVS8wXptFudIdqbLiV7', '8h1nM05brs4UI9JxF112u', 9, 'single', '8h1nM05brs4UI9JxF112u/bRcVS8wXptFudIdqbLiV7.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('Zokm_HPAhhS--M-BKPSyt', '8h1nM05brs4UI9JxF112u', 10, 'single', '8h1nM05brs4UI9JxF112u/Zokm_HPAhhS--M-BKPSyt.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('5WwbC6YJcaGUV1GPdsh8_', '8h1nM05brs4UI9JxF112u', 11, 'single', '8h1nM05brs4UI9JxF112u/5WwbC6YJcaGUV1GPdsh8_.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('NK3FTKwGLR3Z1NDwvJP07', '8h1nM05brs4UI9JxF112u', 12, 'single', '8h1nM05brs4UI9JxF112u/NK3FTKwGLR3Z1NDwvJP07.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('SCV70I5-pnImWHfZNm9lG', '8h1nM05brs4UI9JxF112u', 13, 'single', '8h1nM05brs4UI9JxF112u/SCV70I5-pnImWHfZNm9lG.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('tcopG2gIyO5IDO2msPi47', '8h1nM05brs4UI9JxF112u', 14, 'single', '8h1nM05brs4UI9JxF112u/tcopG2gIyO5IDO2msPi47.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('PeShXxEbedqaLrFH2Q4SR', 'Ki7vphBTNqabA9jhaf5Ub', 0, 'single', 'Ki7vphBTNqabA9jhaf5Ub/PeShXxEbedqaLrFH2Q4SR.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('-vzeAf7sJ1SAs2dgdefHN', 'Ki7vphBTNqabA9jhaf5Ub', 1, 'single', 'Ki7vphBTNqabA9jhaf5Ub/-vzeAf7sJ1SAs2dgdefHN.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('Nj8p_1oAGIZ7QmMb88LzM', 'Ki7vphBTNqabA9jhaf5Ub', 2, 'single', 'Ki7vphBTNqabA9jhaf5Ub/Nj8p_1oAGIZ7QmMb88LzM.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('J5AviGJjKQbeFyGylUPfo', 'Ki7vphBTNqabA9jhaf5Ub', 3, 'single', 'Ki7vphBTNqabA9jhaf5Ub/J5AviGJjKQbeFyGylUPfo.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('x5HCfzavEUB-lsiTbbBzL', 'Ki7vphBTNqabA9jhaf5Ub', 4, 'single', 'Ki7vphBTNqabA9jhaf5Ub/x5HCfzavEUB-lsiTbbBzL.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('f1SLpZaZZtxMTgSBkQV8e', 'Ki7vphBTNqabA9jhaf5Ub', 5, 'single', 'Ki7vphBTNqabA9jhaf5Ub/f1SLpZaZZtxMTgSBkQV8e.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('B1yjCYaI_EB-l8RagMQD9', 'Ki7vphBTNqabA9jhaf5Ub', 6, 'single', 'Ki7vphBTNqabA9jhaf5Ub/B1yjCYaI_EB-l8RagMQD9.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('JdmkRtBoLkb4RyewxGqYQ', 'Ki7vphBTNqabA9jhaf5Ub', 7, 'single', 'Ki7vphBTNqabA9jhaf5Ub/JdmkRtBoLkb4RyewxGqYQ.jpg', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('rENPQteEYQ9fvYmFR3_Lf', '_W3CNdKyEroebstm03uOy', 0, 'single', '_W3CNdKyEroebstm03uOy/rENPQteEYQ9fvYmFR3_Lf.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('TMdaDejZ90vX33Q2gOpv5', '_W3CNdKyEroebstm03uOy', 1, 'single', '_W3CNdKyEroebstm03uOy/TMdaDejZ90vX33Q2gOpv5.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('LIogKFSkqFr30jVKElMGK', '_W3CNdKyEroebstm03uOy', 2, 'single', '_W3CNdKyEroebstm03uOy/LIogKFSkqFr30jVKElMGK.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('qgvJhyQv2VwdzA4J8DQ1Y', '_W3CNdKyEroebstm03uOy', 3, 'single', '_W3CNdKyEroebstm03uOy/qgvJhyQv2VwdzA4J8DQ1Y.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('Q5c2E7w2jmWffBYipURVZ', '_W3CNdKyEroebstm03uOy', 4, 'single', '_W3CNdKyEroebstm03uOy/Q5c2E7w2jmWffBYipURVZ.png', NULL, '', NULL);
INSERT INTO blocks (id, case_study_id, position, layout, image_l_key, image_r_key, alt_l, alt_r) VALUES ('mql3SHzkfNiL3wWmMHeUB', '_W3CNdKyEroebstm03uOy', 5, 'single', '_W3CNdKyEroebstm03uOy/mql3SHzkfNiL3wWmMHeUB.png', NULL, '', NULL);
